DROP TABLE IF EXISTS `radacct`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `radacct` (
  `radacctid` bigint(21) NOT NULL auto_increment,
  `acctsessionid` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `acctuniqueid` varchar(32) collate utf8_unicode_ci NOT NULL default '',
  `username` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `groupname` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `realm` varchar(64) collate utf8_unicode_ci default '',
  `nasipaddress` varchar(15) collate utf8_unicode_ci NOT NULL default '',
  `nasportid` varchar(15) collate utf8_unicode_ci default NULL,
  `nasporttype` varchar(32) collate utf8_unicode_ci default NULL,
  `acctstarttime` datetime default NULL,
  `acctstoptime` datetime default NULL,
  `acctsessiontime` int(12) default NULL,
  `acctauthentic` varchar(32) collate utf8_unicode_ci default NULL,
  `connectinfo_start` varchar(50) collate utf8_unicode_ci default NULL,
  `connectinfo_stop` varchar(50) collate utf8_unicode_ci default NULL,
  `acctinputoctets` bigint(20) default NULL,
  `acctoutputoctets` bigint(20) default NULL,
  `calledstationid` varchar(50) collate utf8_unicode_ci NOT NULL default '',
  `callingstationid` varchar(50) collate utf8_unicode_ci NOT NULL default '',
  `acctterminatecause` varchar(32) collate utf8_unicode_ci NOT NULL default '',
  `servicetype` varchar(32) collate utf8_unicode_ci default NULL,
  `framedprotocol` varchar(32) collate utf8_unicode_ci default NULL,
  `framedipaddress` varchar(15) collate utf8_unicode_ci NOT NULL default '',
  `acctstartdelay` int(12) default NULL,
  `acctstopdelay` int(12) default NULL,
  `xascendsessionsvrkey` varchar(10) collate utf8_unicode_ci default NULL,
  PRIMARY KEY  (`radacctid`),
  KEY `username` (`username`),
  KEY `framedipaddress` (`framedipaddress`),
  KEY `acctsessionid` (`acctsessionid`),
  KEY `acctsessiontime` (`acctsessiontime`),
  KEY `acctuniqueid` (`acctuniqueid`),
  KEY `acctstarttime` (`acctstarttime`),
  KEY `acctstoptime` (`acctstoptime`),
  KEY `nasipaddress` (`nasipaddress`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
SET character_set_client = @saved_cs_client;
